version: '2'
services:

    # Application containers
    go:
        build: .
        command: ["go", "run", "main.go"]
        #volumes:
          #  - .:/go/src/gorestexample
       #working_dir: /go/src/gorestexample
       #command: go run main.go
       #command: go run main.go
        ports:
            - "80:8080"
        links:
            - postgres
        environment:
            DEBUG: 'true'
            PORT: '8080'

    postgres:
        image: onjin/alpine-postgres:9.5
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: gorest
            POSTGRES_PASSWORD: gorest
            POSTGRES_DB: gorest



